spring.application.name=wellu-education-service
server.port=8083

spring.datasource.url=jdbc:postgresql://education-db:5432/education
spring.datasource.username=education
spring.datasource.password=password